### ISSUE TITLE
Bugs in urlEncode

### ISSUE THREAD

**Issue by alesiong** [cuhkshenzhen/CUHKSZLib#35]
In this [test](https://github.com/cuhkshenzhen/CUHKSZLib/blob/master/tests/network/network_functions_test.cpp).
还是用中文说吧，这里字符串里用了unicode字符，但是c++的""和对应的`std::string`只能支持1字节的字符，所以unicode字符会被转换成对应的8位整数。但是在windows上，有保护机制防止字符的取值<0（>128），所以这段代码在windows上会报错。
@Yexiaoxing

**Comment by Yexiaoxing** [comment]
fix
