### ISSUE TITLE
Occasionally misbehavior of BinomialDistribution

### ISSUE THREAD

**Issue by Yexiaoxing** [cuhkshenzhen/CUHKSZLib#47]
BinomialDistribution.real_theory
/home/travis/build/cuhkshenzhen/CUHKSZLib/tests/random/BinomialDistributionTest.cpp:24: Failure
Expected: (error_sum / 11) < (0.05), actual: 0.051477 vs 0.05

Reproductive on my macOS sometimes.

**Comment by alesiong** [comment]
It will be fix in my next pr. Actually if it happens in the ci, just click `restart` and let it run again. If it fails again, you're so lucky...
