### ISSUE TITLE
Add doc generation to CI

### ISSUE THREAD

**Issue by Yexiaoxing** [cuhkshenzhen/CUHKSZLib#53]

**Comment by alesiong** [comment]
Maybe try use this next time https://docs.travis-ci.com/user/deployment/pages/
Note that the encrypted environment variables in travis are only available in branch build, not in pr build.

**Comment by alesiong** [comment]
Create a `document-gen` branch, please do the ci deploy test there

**Comment by alesiong** [comment]
The document generating and deploying will be triggered after something merging into the `master` branch
