### ISSUE TITLE
Provide a `mapAll` function to loop elements

### ISSUE THREAD

**Issue by Yexiaoxing** [cuhkshenzhen/CUHKSZLib#56]
Like what is said in lecture ...

**Comment by alesiong** [comment]
I would prefer a free `map` function, like `void map(Container, Function)`

**Comment by Yexiaoxing** [comment]
http://stackoverflow.com/questions/3580457/stl-name-for-the-map-functional-programming-function

**Comment by Yexiaoxing** [comment]
http://stackoverflow.com/questions/33379145/equivalent-of-python-map-function-using-lambda

**Comment by alesiong** [comment]
#60
