### ISSUE TITLE
error in travis ci

### ISSUE THREAD

**Issue by Yexiaoxing** [cuhkshenzhen/CUHKSZLib#62]
we now auto deploy documents using travis ci, but if we push changes to our forks, the test will go wrong since it has no permission.

**Comment by alesiong** [comment]
As it will push to the repo you are in, you need to add a private token to your repo in travis-ci dashboard, named `GITHUB_TOKEN`
https://docs.travis-ci.com/user/deployment/pages/

**Comment by Yexiaoxing** [comment]
any ability to disable doc generation if `github_token` is unset?

**Comment by alesiong** [comment]
It has been added to wiki
